// ===== Shared Navigation Component =====
// Auto-generated by build.js — do not edit manually

const MODULES = [
  {
    id: 'module0',
    file: 'module0.html',
    number: '0',
    title: 'Avant de commencer',
    steps: [
      { id: 'm0-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm0-etape1', label: 'Étape 1 — Le terminal' },
      { id: 'm0-etape2', label: 'Étape 2 — Visual Studio Code' },
      { id: 'm0-etape3', label: 'Étape 3 — Git' },
      { id: 'm0-etape4', label: 'Étape 4 — Claude Code' },
      { id: 'm0-recap', label: 'Ce que vous avez installé — et pourquoi' },
      { id: 'm0-checkpoint', label: 'Checkpoint' },
    ]
  },
  {
    id: 'module1',
    file: 'module1.html',
    number: '1',
    title: 'Pourquoi ça part en vrille',
    steps: [
      { id: 'm1-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm1-etape1', label: 'Étape 1 — Demandez quelque chose de simple' },
      { id: 'm1-etape2', label: 'Étape 2 — Demandez-lui d\'ajouter des choses' },
      { id: 'm1-etape3', label: 'Étape 3 — Comprendre ce qui s\'est passé' },
      { id: 'm1-etape4', label: 'Étape 4 — Construire un plan' },
      { id: 'm1-repartir', label: 'Repartir de zéro' },
      { id: 'm1-etape5', label: 'Étape 5 — Reconstruire, cette fois avec le plan' },
      { id: 'm1-etape6', label: 'Étape 6 — Le test final' },
      { id: 'm1-bilan', label: 'Ce que vous avez appris' },
    ]
  },
  {
    id: 'module2',
    file: 'module2.html',
    number: '2',
    title: 'Le passage du témoin',
    steps: [
      { id: 'm2-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm2-etape1', label: 'Étape 1 — Provoquer la catastrophe' },
      { id: 'm2-etape2', label: 'Étape 2 — Comprendre le problème' },
      { id: 'm2-etape3', label: 'Étape 3 — Écrire les parcours' },
      { id: 'm2-repartir', label: 'Repartir de zéro — proprement' },
      { id: 'm2-etape4', label: 'Étape 4 — Reconstruire avec les parcours' },
      { id: 'm2-etape5', label: 'Étape 5 — Le scénario impossible' },
      { id: 'm2-etape6', label: 'Étape 6 — Compléter le plan' },
      { id: 'm2-bilan', label: 'Ce que vous avez appris' },
    ]
  },
  {
    id: 'projet1',
    file: 'projet1.html',
    number: 'P1',
    numberStyle: 'background:var(--accent-primary);color:white;font-size:0.65rem;',
    title: 'Projet libre 1',
    steps: [
      { id: 'p1-contexte', label: 'Le contexte' },
      { id: 'p1-phase1', label: 'Phase 1 — Réfléchir seul' },
      { id: 'p1-phase2', label: 'Phase 2 — Écrire le plan' },
      { id: 'p1-phase3', label: 'Phase 3 — Confronter à Claude' },
      { id: 'p1-phase4', label: 'Phase 4 — Le vrai test' },
      { id: 'p1-eval', label: 'Auto-évaluation' },
    ]
  },
  {
    id: 'module3',
    file: 'module3.html',
    number: '3',
    title: 'La carte et le territoire',
    steps: [
      { id: 'm3-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm3-etape1', label: 'Étape 1 — Provoquer le problème' },
      { id: 'm3-etape2', label: 'Étape 2 — Comprendre le problème' },
      { id: 'm3-etape3', label: 'Étape 3 — Créer les fiches' },
      { id: 'm3-repartir', label: 'Repartir de zéro — avec le nouveau plan' },
      { id: 'm3-etape4', label: 'Étape 4 — Reconstruire avec les niveaux de zoom' },
      { id: 'm3-etape5', label: 'Étape 5 — Écrire une fiche vous-même' },
      { id: 'm3-etape6', label: 'Étape 6 — Le test des deux conversations' },
      { id: 'm3-etape7', label: 'Étape 7 — Mettre à jour la vue d\'ensemble' },
      { id: 'm3-bilan', label: 'Ce que vous avez appris' },
    ]
  },
  {
    id: 'module4',
    file: 'module4.html',
    number: '4',
    title: 'Faire confiance, mais vérifier',
    steps: [
      { id: 'm4-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm4-etape1', label: 'Étape 1 — Construire un terrain d\'entraînement' },
      { id: 'm4-etape2', label: 'Étape 2 — Tester vous-même d\'abord' },
      { id: 'm4-etape3', label: 'Étape 3 — Le vérificateur' },
      { id: 'm4-etape4', label: 'Étape 4 — Comprendre la différence' },
      { id: 'm4-etape5', label: 'Étape 5 — Écrire des vérifications' },
      { id: 'm4-etape6', label: 'Étape 6 — Le cycle de correction' },
      { id: 'm4-etape7', label: 'Étape 7 — Les tests automatiques' },
      { id: 'm4-bilan', label: 'Ce que vous avez appris' },
    ]
  },
  {
    id: 'module5',
    file: 'module5.html',
    number: '5',
    title: 'Vérifier pour de vrai',
    steps: [
      { id: 'm5-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm5-etape1', label: 'Étape 1 — Écrire les vérifications dans les fiches' },
      { id: 'm5-etape2', label: 'Étape 2 — Le rapport de vérification' },
      { id: 'm5-etape3', label: 'Étape 3 — Prioriser' },
      { id: 'm5-etape4', label: 'Étape 4 — Le cycle de correction' },
      { id: 'm5-etape5', label: 'Étape 5 — Les tests automatiques' },
      { id: 'm5-etape6', label: 'Étape 6 — Élargir à d\'autres fiches' },
      { id: 'm5-bilan', label: 'Ce que vous avez appris' },
    ]
  },
  {
    id: 'module6',
    file: 'module6.html',
    number: '6',
    title: 'Les vrais mots, les vraies décisions',
    steps: [
      { id: 'm6-etape1', label: 'Étape 1 — Apprendre les vrais noms' },
      { id: 'm6-etape2', label: 'Étape 2 — Comprendre les invariants' },
      { id: 'm6-etape3', label: 'Étape 3 — Le changement qui casse tout' },
      { id: 'm6-etape4', label: 'Étape 4 — Faire la refonte' },
      { id: 'm6-etape5', label: 'Étape 5 — Le vocabulaire en action' },
      { id: 'm6-bilan', label: 'Ce que vous avez appris' },
    ]
  },
  {
    id: 'module7',
    file: 'module7.html',
    number: '7',
    title: 'La bascule',
    steps: [
      { id: 'm7-analogie', label: 'L\'analogie' },
    ]
  },
  {
    id: 'module8',
    file: 'module8.html',
    number: '8',
    title: 'Les mains dans le moteur',
    steps: [
      { id: 'm8-jour1', label: 'Jour 1 — Installer et découvrir' },
      { id: 'm8-jour2', label: 'Jour 2 — Lire le code' },
      { id: 'm8-jour3', label: 'Jour 3 — Construire naïvement' },
      { id: 'm8-jour4', label: 'Jour 4 — Lire les résultats dans le code' },
      { id: 'm8-jour5', label: 'Jour 5 — Ajouter des fonctionnalités' },
      { id: 'm8-jour6', label: 'Jour 6 — Découper' },
      { id: 'm8-jour7', label: 'Jour 7 — Le bilan' },
    ]
  },
  {
    id: 'module9',
    file: 'module9.html',
    number: '9',
    title: 'Le monolithe qui enfle',
    steps: [
      { id: 'm9-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm9-jour1', label: 'Jour 1 — Voir les fils emmêlés' },
      { id: 'm9-jour2', label: 'Jour 2 — Provoquer la douleur' },
      { id: 'm9-jour3', label: 'Jour 3 — Penser en événements' },
      { id: 'm9-jour4', label: 'Jour 4 — Transformer les appels en événements' },
      { id: 'm9-jour5', label: 'Jour 5 — Les tests cassent' },
      { id: 'm9-jour6', label: 'Jour 6 — Le vocabulaire du jour' },
      { id: 'm9-jour7', label: 'Jour 7 — Le bilan' },
    ]
  },
  {
    id: 'module10',
    file: 'module10.html',
    number: '10',
    title: 'Les mots du métier',
    steps: [
      { id: 'm10-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm10-jour1', label: 'Jour 1 — Écouter les utilisateurs' },
      { id: 'm10-jour2', label: 'Jour 2 — Regarder le code avec les yeux du gérant' },
      { id: 'm10-jour3', label: 'Jour 3 — Les choses qui vont ensemble' },
      { id: 'm10-jour4', label: 'Jour 4 — Les choses qui ont une valeur, pas une identité' },
      { id: 'm10-jour5', label: 'Jour 5 — Réécrire le code en langage du domaine' },
      { id: 'm10-jour6', label: 'Jour 6 — Vérifier que tout tient' },
      { id: 'm10-jour7', label: 'Jour 7 — Le bilan et le nouveau vocabulaire' },
    ]
  },
  {
    id: 'module11',
    file: 'module11.html',
    number: '11',
    title: 'Les frontières qui tiennent',
    steps: [
      { id: 'm11-analogie', label: 'Avant de commencer : une analogie' },
      { id: 'm11-jour1', label: 'Jour 1 — Le problème de la base de données' },
      { id: 'm11-jour2', label: 'Jour 2 — Un agrégat qui vit en mémoire' },
      { id: 'm11-jour3', label: 'Jour 3 — Que se passe-t-il quand le guichet plante ?' },
      { id: 'm11-jour4', label: 'Jour 4 — Synchroniser le processus et la base' },
      { id: 'm11-jour5', label: 'Jour 5 — L\'arbre de supervision complet' },
      { id: 'm11-jour6', label: 'Jour 6 — Relier les processus et les événements' },
      { id: 'm11-jour7', label: 'Jour 7 — Le bilan' },
    ]
  }
];


function getCurrentModuleId() {
  const page = location.pathname.split('/').pop().replace('.html', '');
  const mod = MODULES.find(m => m.file.replace('.html', '') === page);
  return mod ? mod.id : MODULES[0].id;
}

function buildSidebar() {
  const root = document.getElementById('sidebar-root');
  if (!root) return;

  const currentId = getCurrentModuleId();
  const currentIndex = MODULES.findIndex(m => m.id === currentId);

  // Build module nav items
  let modulesHtml = '';
  MODULES.forEach(mod => {
    const isActive = mod.id === currentId;
    const numStyle = mod.numberStyle ? ` style="${mod.numberStyle}"` : '';

    let stepsHtml = '';
    mod.steps.forEach(step => {
      const href = mod.id === currentId
        ? `#${step.id}`
        : `${mod.file}#${step.id}`;
      stepsHtml += `<a class="sidebar-step" href="${href}" data-section="${step.id}">${step.label}</a>`;
    });

    modulesHtml += `
      <div class="sidebar-module${isActive ? ' open' : ''}">
        <div class="sidebar-module-header${isActive ? ' active' : ''}" data-module="${mod.id}" data-file="${mod.file}">
          <span class="sidebar-module-number"${numStyle}>${mod.number}</span>
          ${mod.title}
          <span class="chevron">▶</span>
        </div>
        <div class="sidebar-steps">${stepsHtml}</div>
      </div>`;
  });

  // Progress
  const pct = Math.round(((currentIndex + 1) / MODULES.length) * 100);
  const label = MODULES[currentIndex]
    ? (MODULES[currentIndex].number.length <= 2 ? `Module ${MODULES[currentIndex].number}` : MODULES[currentIndex].title)
    : '';

  root.innerHTML = `
    <button class="sidebar-toggle" aria-label="Menu">☰</button>
    <div class="sidebar-overlay"></div>
    <aside class="sidebar">
      <div class="sidebar-header">
        <div class="sidebar-brand">Construire avec <span>l'IA</span></div>
        <div class="sidebar-subtitle">Partie 1 — Penser en architecte</div>
      </div>
      <nav class="sidebar-nav">
        <div class="sidebar-section">
          <div class="sidebar-section-label">Modules</div>
          ${modulesHtml}
        </div>
      </nav>
      <div class="sidebar-progress">
        <div class="progress-label">${label} — ${pct}%</div>
        <div class="progress-bar"><div class="progress-fill" style="width:${pct}%"></div></div>
      </div>
    </aside>`;

  // Bind events
  initSidebarEvents();
}

function initSidebarEvents() {
  // Module headers: click to navigate or toggle
  document.querySelectorAll('.sidebar-module-header').forEach(header => {
    header.addEventListener('click', () => {
      const file = header.dataset.file;
      const currentPage = location.pathname.split('/').pop();

      if (file === currentPage) {
        // Same page: toggle steps
        const parent = header.closest('.sidebar-module');
        parent.classList.toggle('open');
      } else {
        // Navigate to other page
        location.href = file;
      }
    });
  });

  // Steps on current page: smooth scroll
  document.querySelectorAll('.sidebar-step').forEach(step => {
    step.addEventListener('click', (e) => {
      const href = step.getAttribute('href');
      if (href.startsWith('#')) {
        e.preventDefault();
        const target = document.getElementById(href.slice(1));
        if (target) {
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
        // Update active
        document.querySelectorAll('.sidebar-step').forEach(s => s.classList.remove('active'));
        step.classList.add('active');
        // Close mobile
        closeMobileMenu();
      }
      // External links (other pages) just follow the href naturally
    });
  });

  // Mobile menu
  const toggle = document.querySelector('.sidebar-toggle');
  const overlay = document.querySelector('.sidebar-overlay');
  if (toggle) {
    toggle.addEventListener('click', () => {
      document.querySelector('.sidebar').classList.toggle('open');
      overlay.classList.toggle('visible');
    });
  }
  if (overlay) {
    overlay.addEventListener('click', closeMobileMenu);
  }
}

function closeMobileMenu() {
  const sidebar = document.querySelector('.sidebar');
  const overlay = document.querySelector('.sidebar-overlay');
  if (sidebar) sidebar.classList.remove('open');
  if (overlay) overlay.classList.remove('visible');
}

// Init on load
document.addEventListener('DOMContentLoaded', buildSidebar);
